#!/usr/bin/env bash
#
# Build a minimal OpenCV.js with only the modules this app uses.
#
# Why: the official OpenCV.js at docs.opencv.org is ~8 MB and takes 3-5 s
# to compile (even in a Web Worker). This script produces a slimmed-down
# build that includes ONLY the `imgproc` and `core` modules — enough for
# threshold / cvtColor / findContours / approxPolyDP / arcLength /
# contourArea / boundingRect / matFromImageData.
#
# Expected output: ~1.5-2 MB → ~500 ms-1 s compile in the worker.
#
# Requirements: Docker. The script does NOT touch your local toolchain;
# emscripten runs inside the `emscripten/emsdk` container.
#
# First run takes 15-30 min (clone OpenCV + compile). Subsequent runs reuse
# the cached clone and rebuild in ~5 min.
#
# Usage:
#   ./scripts/build-opencv.sh
#
# Output goes to public/opencv-min.js (and public/opencv_js.wasm).
# The worker (src/cv/cvWorker.js) detects these files automatically.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$PROJECT_ROOT/.opencv-build"
OPENCV_VERSION="4.10.0"
PUBLIC_DIR="$PROJECT_ROOT/public"

# Sanity checks ---------------------------------------------------------------
if ! command -v docker &>/dev/null; then
  cat <<'EOF' >&2
ERROR: Docker is not installed or not on PATH.

This script uses Docker to run emscripten in a container, so you don't have
to install the emscripten SDK locally (which is ~3 GB on its own).

Install Docker Desktop:    https://www.docker.com/products/docker-desktop/
Then re-run this script.
EOF
  exit 1
fi

if ! docker info &>/dev/null; then
  echo "ERROR: Docker daemon isn't running. Start Docker Desktop and retry." >&2
  exit 1
fi

# 1. Clone OpenCV (cached across runs) ----------------------------------------
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

if [ ! -d "opencv" ]; then
  echo "==> Cloning OpenCV $OPENCV_VERSION (~500 MB, one-time)…"
  git clone --depth 1 --branch "$OPENCV_VERSION" \
    https://github.com/opencv/opencv.git
else
  echo "==> Reusing existing OpenCV clone at $BUILD_DIR/opencv"
fi

# 2. Inject a minimal whitelist config -----------------------------------------
# OpenCV.js uses a Python "whitelist" file to decide which classes and
# functions get exported into the JS bindings. The default whitelist exports
# almost everything in core + imgproc + others. We replace it with a tight
# whitelist containing only the symbols our worker uses.

WHITELIST="$BUILD_DIR/opencv/platforms/js/opencv_js.config.py"

cat > "$WHITELIST" <<'PYEOF'
# Minimal whitelist generated by scripts/build-opencv.sh
# Keeps only what src/cv/cvWorker.js calls.

core = {
    'Mat': [
        'Mat',
        'data',
        'cols',
        'rows',
        'channels',
        'convertTo',
        'delete',
        'isContinuous',
        'setTo',
        'type',
        'roi',
    ],
    '': [
        'matFromImageData',
        'matFromArray',
    ],
}

imgproc = {
    '': [
        'cvtColor',
        'threshold',
        'findContours',
        'contourArea',
        'arcLength',
        'approxPolyDP',
        'boundingRect',
    ],
}

video = {}
dnn = {}
features2d = {}
photo = {}
aruco = {}
calib3d = {}
objdetect = {}

white_list = makeWhiteList([core, imgproc])
PYEOF

# 3. Build via the official emscripten Docker image ---------------------------
# The OpenCV build_js.py script bootstraps everything inside the container.
# We pass --cmake_option to disable the modules we don't need and shrink the
# output further.

echo "==> Building minimal OpenCV.js (this is the slow part — 10-25 min)…"
echo "    Build dir: $BUILD_DIR/opencv/build_wasm"
echo "    Docker image: emscripten/emsdk:3.1.64"
echo

docker run --rm \
  -v "$BUILD_DIR/opencv:/src" \
  -w /src \
  --user "$(id -u):$(id -g)" \
  emscripten/emsdk:3.1.64 \
  bash -lc "
    set -e
    python platforms/js/build_js.py build_wasm \
      --build_wasm \
      --disable_single_file \
      --cmake_option='-DBUILD_LIST=imgproc,core' \
      --cmake_option='-DWITH_PNG=OFF' \
      --cmake_option='-DWITH_JPEG=OFF' \
      --cmake_option='-DWITH_TIFF=OFF' \
      --cmake_option='-DWITH_WEBP=OFF' \
      --cmake_option='-DBUILD_opencv_calib3d=OFF' \
      --cmake_option='-DBUILD_opencv_dnn=OFF' \
      --cmake_option='-DBUILD_opencv_features2d=OFF' \
      --cmake_option='-DBUILD_opencv_flann=OFF' \
      --cmake_option='-DBUILD_opencv_ml=OFF' \
      --cmake_option='-DBUILD_opencv_objdetect=OFF' \
      --cmake_option='-DBUILD_opencv_photo=OFF' \
      --cmake_option='-DBUILD_opencv_stitching=OFF' \
      --cmake_option='-DBUILD_opencv_video=OFF' \
      --cmake_option='-DBUILD_opencv_videoio=OFF'
  "

# 4. Copy output into public/ -------------------------------------------------
SRC_JS="$BUILD_DIR/opencv/build_wasm/bin/opencv.js"
SRC_WASM="$BUILD_DIR/opencv/build_wasm/bin/opencv_js.wasm"

if [ ! -f "$SRC_JS" ]; then
  echo "ERROR: build finished but $SRC_JS is missing — check Docker output above." >&2
  exit 1
fi

mkdir -p "$PUBLIC_DIR"
cp "$SRC_JS" "$PUBLIC_DIR/opencv-min.js"
[ -f "$SRC_WASM" ] && cp "$SRC_WASM" "$PUBLIC_DIR/opencv_js.wasm"

echo
echo "==> Done."
echo "    Output:  $PUBLIC_DIR/opencv-min.js  ($(du -h "$PUBLIC_DIR/opencv-min.js" | cut -f1))"
[ -f "$PUBLIC_DIR/opencv_js.wasm" ] && \
  echo "             $PUBLIC_DIR/opencv_js.wasm   ($(du -h "$PUBLIC_DIR/opencv_js.wasm" | cut -f1))"
echo
echo "    The worker will pick this up automatically on next page load."
echo "    Hard-refresh the browser (Cmd+Shift+R) to bust any caches."
